name: Experimental

on:
  push:
    branches:
      - master
      - 'releases/*'
  pull_request:
    branches:
      - '*'

jobs:
  openjdk14:
    name: OpenJDK 14
    runs-on: ubuntu-latest
    container: junitteam/build:latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      run: |
        export JAVA_HOME=$JDK13
        ./gradlew --version
        ./gradlew --scan --warning-mode=all -Dplatform.tooling.support.tests.enabled=true -PjavaHome=$JDK14 build
